server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_portal
    username: postgres
    password: yourpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
